#comment out unless debugging
#FLAGS = -std=gnu99 -DDEBUG -Wall -lpthread
FLAGS = -std=gnu99 -Wall -lpthread

ex7: ex7_runner.c ex7_mmalloc.c
	gcc $(FLAGS) ex7_runner.c ex7_mmalloc.c -o ex7

clean:
	rm ex7

