#uncomment this for debug
#FLAGS = -std=gnu99 -DDEBUG -Wall -lpthread
FLAGS = -std=gnu99 -Wall -lpthread

ex6: ex6_runner.c ex6_mmalloc.c
	gcc $(FLAGS) ex6_runner.c ex6_mmalloc.c -o ex6

clean:
	rm ex6

