#uncomment this for debug
#FLAGS = -std=gnu99 -DDEBUG -Wall -lpthread
FLAGS = -std=gnu99 -Wall -lpthread

ex3: ex3_runner.c ex3_mmalloc.c
	gcc $(FLAGS) ex3_runner.c ex3_mmalloc.c -o ex3

clean:
	rm ex3

